Add NAPALM & LDAP Support
pitkley/docker-netbox pull request #18
Opened 2018-10-17 15:18 UTC by rcmurphy

2018-10-17 15:19 UTC, rcmurphy commented on Dockerfile
> +    && (pip install --no-cache-dir django-auth-ldap napalm)
This is here instead of above because we don't want to reinstall Django.

2018-11-18 12:07 UTC, pitkley requested changes
Hi @rcmurphy, sorry for not responding sooner. Thanks for the PR, the changes look very sensible. Though I have to agree with you: I'm not sure if this would be right for `master`/`develop`.

I have no objections to having these changes on a separate branch though. I have created an `ldap` branch for you to point your PR at. Once the PR is merged, I'll setup Docker Hub to build a tag `ldap` off of this new branch.

Does this sound good to you?

2018-11-19 17:19 UTC, rcmurphy commented
@pitkley sounds great! I changed the base as requested; thanks for being willing to do that!

2018-11-19 20:21 UTC, pitkley approved these changes

2018-11-19 20:22 UTC, merged

2018-11-19 20:33 UTC, pitkley commented
@rcmurphy the Docker Hub tag has been built. :+1: 

I'll try to keep the `ldap` branch up-to-date with `master` whenever I get to updating it. Thanks for the contribution. :slightly_smiling_face: